### ISSUE TITLE
안녕하세요. EPG 연동 문의드립니다.

### ISSUE THREAD

**Issue by HWANKILEE** [wiserain/epg2xml#4]
안녕하세요.
최근 wiserain/tvheadend를 재설치 하였는데요.
재설치후 EPG를 못받아오는 문제가 발생해서 글을 작성합니다.
초보적인 문제일수도 있어서 먼저 죄송한 말씀 드립니다.

기존에 하던대로 내부그래버 SK 켜고, epg2xml.json 파일을 도커에 마운트한 epg2xml 폴더에 넣어줬습니다. tvheadend 로그에서 아래와 같은 오류가 발생하는데요. 어떻게 하면 해결할 수 있는지 궁금합니다.

혹시몰라 이전에 잘 사용하던 epg2xml.py 파일로 덮어쓰고 해봐도 같은 오류가 발생해서요ㅠ

2020-05-10 13:57:48.000 xmltv: /usr/bin/tv_grab_kr_sk: grab /usr/bin/tv_grab_kr_sk
2020-05-10 13:57:48.000 spawn: Executing "/usr/bin/tv_grab_kr_sk"
2020-05-10 13:57:48.338 spawn: Traceback (most recent call last):
2020-05-10 13:57:48.338 spawn:   File "/epg2xml/epg2xml.py", line 59, in 
2020-05-10 13:57:48.338 spawn:     filehandler = RotatingFileHandler(args['logfile'], maxBytes=1024 * 1000, backupCount=5, encoding='utf-8')
2020-05-10 13:57:48.338 spawn:   File "/usr/lib/python3.8/logging/handlers.py", line 148, in __init__
2020-05-10 13:57:48.338 spawn:     BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
2020-05-10 13:57:48.338 spawn:   File "/usr/lib/python3.8/logging/handlers.py", line 55, in __init__
2020-05-10 13:57:48.338 spawn:     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
2020-05-10 13:57:48.338 spawn:   File "/usr/lib/python3.8/logging/__init__.py", line 1143, in __init__
2020-05-10 13:57:48.339 spawn:     StreamHandler.__init__(self, self._open())
2020-05-10 13:57:48.339 spawn:   File "/usr/lib/python3.8/logging/__init__.py", line 1172, in _open
2020-05-10 13:57:48.340 spawn:     return open(self.baseFilename, self.mode, encoding=self.encoding)
2020-05-10 13:57:48.340 spawn: PermissionError: [Errno 13] Permission denied: '/epg2xml/epg2xml.py.log'
2020-05-10 13:57:48.353 spawn: cat: /epg2xml/xml/xmltv.xml: No such file or directory
2020-05-10 13:57:48.353 xmltv: /usr/bin/tv_grab_kr_sk: no output detected
2020-05-10 13:57:48.353 xmltv: /usr/bin/tv_grab_kr_sk: grab returned no data

감사합니다.

**Comment by wiserain** [comment]
폴더 혹은 파일에 권한이 없어서 쓰지 못하고 있네요. chown 같은걸로 바꿔주시고 도커라면 PUID PGID도 잘 넣어서 컨테이너 생성/실행하세요.

**Comment by HWANKILEE** [comment]
> 폴더 혹은 파일에 권한이 없어서 쓰지 못하고 있네요. chown 같은걸로 바꿔주시고 도커라면 PUID PGID도 잘 넣어서 컨테이너 생성/실행하세요.

역시나 제가 기초적인 부분을 놓친거였습니다.. 죄송합니다ㅜ.ㅜ 도커에서 PUID / PGID 부여후에 정상적으로 EPG 수집되었습니다. 주말 즐겁게 마무리하시고 정말 감사합니다!
